<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-VFTDAVM" failures="2" tests="2" name="testRunners.Fail_Runner" time="98.965" errors="0" timestamp="29 Jun 2021 05:31:37 GMT" skipped="0">
  <testcase classname="testRunners.Fail_Runner" name="runScenario" time="51.122">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.fail(Assert.java:96)
at stepDefination.SearchBoxSteps.validate_the_outcomes_is_as_per_search_result(SearchBoxSteps.java:60)
at ✽.validate the outcomes is as per search result(file:///C:/Users/Archana%20M/eclipse-workspace/storeManger_New/src/test/resources/com/features/Searchpage.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunners.Fail_Runner" name="runScenario" time="47.843">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.fail(Assert.java:96)
at stepDefination.SearchBoxSteps.validate_the_outcomes_is_as_per_search_result(SearchBoxSteps.java:60)
at ✽.validate the outcomes is as per search result(file:///C:/Users/Archana%20M/eclipse-workspace/storeManger_New/src/test/resources/com/features/Searchpage.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testRunners.Fail_Runner -->
